/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controle.Cadastro;
import controle.Funcionario;
import javax.swing.JOptionPane;
import modelo.CadastroDao;
import modelo.FuncionarioDao;

/**
 *
 * @author Olivercom
 */
public class TelaFuncionario extends javax.swing.JDialog {  
    FrmPrincipal frm = new FrmPrincipal();
    int codigoAtualizacao;
    /**
     * Creates new form TelaFuncionario
     */
    public TelaFuncionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
     public TelaFuncionario(Funcionario f){
        
        initComponents();
     
     codigoAtualizacao = f.getCod();
     
      //JOptionPane.showMessageDialog(rootPane, nome+" "+doc+" "+end+" "+tel+" "+cid);
    txtNomeCadFunc.setText(f.getNomeFunc().toString());
      txtDocCadFunc.setText(f.getDocumento().toString());
       txtEmpCadFunc.setText(f.getEmpresa().toString());
      txtFunCadFunc.setText(f.getFuncao().toString());
      txtTelCadFunc.setText(f.getTelefone().toString());
       txtEndCadFunc.setText(f.getEndereco().toString());
       txtCidCadFunc.setText(f.getCidade().toString());
       jbSalvarCadFunc.setText("ATUALIZAR");
       
    }

   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPCentro = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtFunCadFunc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNomeCadFunc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDocCadFunc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmpCadFunc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelCadFunc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCidCadFunc = new javax.swing.JTextField();
        txtEndCadFunc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jbLimparCadFunc = new javax.swing.JButton();
        jbSalvarCadFunc = new javax.swing.JButton();
        jbCancelacadFunc = new javax.swing.JButton();
        jPTitulo = new javax.swing.JPanel();
        jL_img_titulo = new javax.swing.JLabel();
        jLabel_titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPCentro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPCentro.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Função :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 47, 0, 0);
        jPCentro.add(jLabel4, gridBagConstraints);

        txtFunCadFunc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtFunCadFunc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFunCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFunCadFuncActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 228;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPCentro.add(txtFunCadFunc, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Nome :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 47, 0, 0);
        jPCentro.add(jLabel1, gridBagConstraints);

        txtNomeCadFunc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNomeCadFunc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 228;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 10, 0, 0);
        jPCentro.add(txtNomeCadFunc, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("RG/Cpf :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 47, 0, 0);
        jPCentro.add(jLabel2, gridBagConstraints);

        txtDocCadFunc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDocCadFunc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 228;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPCentro.add(txtDocCadFunc, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Empresa :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 47, 0, 0);
        jPCentro.add(jLabel3, gridBagConstraints);

        txtEmpCadFunc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtEmpCadFunc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 228;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPCentro.add(txtEmpCadFunc, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Telefone :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 47, 0, 0);
        jPCentro.add(jLabel6, gridBagConstraints);

        txtTelCadFunc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtTelCadFunc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 228;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPCentro.add(txtTelCadFunc, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Cidade :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 47, 0, 0);
        jPCentro.add(jLabel7, gridBagConstraints);

        txtCidCadFunc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCidCadFunc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 228;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPCentro.add(txtCidCadFunc, gridBagConstraints);

        txtEndCadFunc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtEndCadFunc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 228;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPCentro.add(txtEndCadFunc, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Endereço :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 47, 0, 0);
        jPCentro.add(jLabel8, gridBagConstraints);

        jbLimparCadFunc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbLimparCadFunc.setText("Limpar");
        jbLimparCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparCadFuncActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 30, 38, 0);
        jPCentro.add(jbLimparCadFunc, gridBagConstraints);

        jbSalvarCadFunc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbSalvarCadFunc.setText("Salvar");
        jbSalvarCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarCadFuncActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 91, 38, 0);
        jPCentro.add(jbSalvarCadFunc, gridBagConstraints);

        jbCancelacadFunc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbCancelacadFunc.setText("Cancelar");
        jbCancelacadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelacadFuncActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 32, 38, 73);
        jPCentro.add(jbCancelacadFunc, gridBagConstraints);

        getContentPane().add(jPCentro, java.awt.BorderLayout.CENTER);

        jPTitulo.setBackground(new java.awt.Color(102, 102, 102));

        jL_img_titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/process32.png"))); // NOI18N
        jPTitulo.add(jL_img_titulo);

        jLabel_titulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_titulo.setText("CADASTRO PRESTADOR DE SERVIÇOS");
        jPTitulo.add(jLabel_titulo);

        getContentPane().add(jPTitulo, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarCadFuncActionPerformed
       //teste();
       if(jbSalvarCadFunc.getText() == "Salvar"){
        Funcionario f = new Funcionario();
        FuncionarioDao  fd = new FuncionarioDao();
        f.setCod(codigoAtualizacao);
        f.setNomeFunc(txtNomeCadFunc.getText());
        f.setDocumento(txtDocCadFunc.getText());
        f.setEmpresa(txtEmpCadFunc.getText());
        f.setFuncao(txtFunCadFunc.getText());
        f.setTelefone(txtTelCadFunc.getText());
        f.setEndereco(txtEndCadFunc.getText());
        f.setCidade(txtCidCadFunc.getText());
        fd.inserir(f);
       frm.preencherTableFunc();
       }else{
          Editar();
       }
    }//GEN-LAST:event_jbSalvarCadFuncActionPerformed

    private void txtFunCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFunCadFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFunCadFuncActionPerformed

    private void jbLimparCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparCadFuncActionPerformed
       clean();
    }//GEN-LAST:event_jbLimparCadFuncActionPerformed

    private void jbCancelacadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelacadFuncActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelacadFuncActionPerformed
    public void clean(){
     txtNomeCadFunc.setText("");
     txtDocCadFunc.setText("");
     txtFunCadFunc.setText("");
     txtEmpCadFunc.setText("");
     txtEndCadFunc.setText("");
     txtTelCadFunc.setText("");
     txtCidCadFunc.setText("");
    }
    public void Editar(){
        Funcionario f = new Funcionario();
        FuncionarioDao  fd = new FuncionarioDao();
        JOptionPane.showMessageDialog(null, "codigo"+codigoAtualizacao);
        f.setCod(codigoAtualizacao);
        f.setNomeFunc(txtNomeCadFunc.getText());
        f.setDocumento(txtDocCadFunc.getText());
        f.setEmpresa(txtEmpCadFunc.getText());
         f.setFuncao(txtFunCadFunc.getText());
        f.setTelefone(txtTelCadFunc.getText());
        f.setEndereco(txtEndCadFunc.getText());
        f.setCidade(txtCidCadFunc.getText());
        fd.atualiza(f);
    }
    public void teste(){
        JOptionPane.showMessageDialog(null, "nao implementado \n Aguarde....");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaFuncionario dialog = new TelaFuncionario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_img_titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JPanel jPCentro;
    private javax.swing.JPanel jPTitulo;
    private javax.swing.JButton jbCancelacadFunc;
    private javax.swing.JButton jbLimparCadFunc;
    private javax.swing.JButton jbSalvarCadFunc;
    private javax.swing.JTextField txtCidCadFunc;
    private javax.swing.JTextField txtDocCadFunc;
    private javax.swing.JTextField txtEmpCadFunc;
    private javax.swing.JTextField txtEndCadFunc;
    private javax.swing.JTextField txtFunCadFunc;
    private javax.swing.JTextField txtNomeCadFunc;
    private javax.swing.JTextField txtTelCadFunc;
    // End of variables declaration//GEN-END:variables
}
