/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author Automacao
 */
public class TelaAbout extends javax.swing.JDialog {

    /**
     * Creates new form TelaAbout
     */
    public TelaAbout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTitulo = new javax.swing.JPanel();
        jL_img_logo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_dados_software = new javax.swing.JTextArea();
        jB_fechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jL_img_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logotipo_base.JPG"))); // NOI18N
        jL_img_logo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTitulo.add(jL_img_logo);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Software para o componente curricular PROJETO INTEGRADOR VI.");
        jTitulo.add(jLabel3);

        getContentPane().add(jTitulo, java.awt.BorderLayout.PAGE_START);

        jPCentro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jT_dados_software.setColumns(20);
        jT_dados_software.setRows(5);
        jScrollPane1.setViewportView(jT_dados_software);

        jB_fechar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jB_fechar.setText("Fechar");
        jB_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_fecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCentroLayout = new javax.swing.GroupLayout(jPCentro);
        jPCentro.setLayout(jPCentroLayout);
        jPCentroLayout.setHorizontalGroup(
            jPCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPCentroLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jB_fechar)
                .addContainerGap(282, Short.MAX_VALUE))
        );
        jPCentroLayout.setVerticalGroup(
            jPCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jB_fechar)
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_fecharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_fecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaAbout dialog = new TelaAbout(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_fechar;
    private javax.swing.JLabel jL_img_logo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPCentro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jT_dados_software;
    private javax.swing.JPanel jTitulo;
    // End of variables declaration//GEN-END:variables
}
