/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author Automacao
 */
public class TelaAjuda extends javax.swing.JDialog {

    /**
     * Creates new form TelaAjuda
     */
    public TelaAjuda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCentro = new javax.swing.JPanel();
        jB_sair = new javax.swing.JButton();
        jLabel_img_ajuda = new javax.swing.JLabel();
        jPTitulo = new javax.swing.JPanel();
        jLabel_img_titulo = new javax.swing.JLabel();
        jLabel_titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jB_sair.setText("Sair");
        jB_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_sairActionPerformed(evt);
            }
        });

        jLabel_img_ajuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ajuda_Principal_r.png"))); // NOI18N

        javax.swing.GroupLayout jPCentroLayout = new javax.swing.GroupLayout(jPCentro);
        jPCentro.setLayout(jPCentroLayout);
        jPCentroLayout.setHorizontalGroup(
            jPCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCentroLayout.createSequentialGroup()
                .addGroup(jPCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCentroLayout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jB_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPCentroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_img_ajuda)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPCentroLayout.setVerticalGroup(
            jPCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_img_ajuda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jB_sair)
                .addContainerGap())
        );

        getContentPane().add(jPCentro, java.awt.BorderLayout.CENTER);

        jPTitulo.setBackground(new java.awt.Color(102, 102, 102));

        jLabel_img_titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/help32.png"))); // NOI18N
        jPTitulo.add(jLabel_img_titulo);

        jLabel_titulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_titulo.setText("Ajuda");
        jPTitulo.add(jLabel_titulo);

        getContentPane().add(jPTitulo, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_sairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jB_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAjuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAjuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAjuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAjuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaAjuda dialog = new TelaAjuda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_sair;
    private javax.swing.JLabel jLabel_img_ajuda;
    private javax.swing.JLabel jLabel_img_titulo;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JPanel jPCentro;
    private javax.swing.JPanel jPTitulo;
    // End of variables declaration//GEN-END:variables
}
