/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controle.Orcamento;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.OrcamentoDao;

/**
 *
 * @author Olivercom
 */
public class TelaOrcamento extends javax.swing.JDialog {

    FrmPrincipal frm = new FrmPrincipal();
    int codigoAtualizacao;

    /**
     * Creates new form TelaOrcamento
     */
    public TelaOrcamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        clean();
    }

    public TelaOrcamento(Orcamento o) {
        initComponents();
        codigoAtualizacao = o.getCod();
        txtDiscriOrcamento.setText(o.getDiscricao().toString());
        txtEmpOrcamento.setText(o.getEmpresa().toString());
        txtTelCadOrcamento.setText(o.getTelefone().toString());
        jDChooser.setDate(o.getDate());
        txtAreaObsCadOrcamento.setText(o.getObs().toString());
        jbSalvarOrcamento.setText("ATUALIZAR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPCentro = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jP_text_area = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaObsCadOrcamento = new javax.swing.JTextArea();
        jbSalvarOrcamento = new javax.swing.JButton();
        jblimparOrcamento = new javax.swing.JButton();
        jbCancOrcamento = new javax.swing.JButton();
        txtDiscriOrcamento = new javax.swing.JTextField();
        txtTelCadOrcamento = new javax.swing.JTextField();
        txtEmpOrcamento = new javax.swing.JTextField();
        jDChooser = new com.toedter.calendar.JDateChooser();
        jTitulo = new javax.swing.JPanel();
        jLabel_img_titulo = new javax.swing.JLabel();
        jLabel_titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPCentro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPCentro.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Data :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 80, 0, 0);
        jPCentro.add(jLabel4, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Discrição :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(57, 80, 0, 0);
        jPCentro.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Empresa :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 80, 0, 0);
        jPCentro.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Telefone :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 80, 0, 0);
        jPCentro.add(jLabel3, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Observações :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 80, 0, 0);
        jPCentro.add(jLabel6, gridBagConstraints);

        txtAreaObsCadOrcamento.setColumns(20);
        txtAreaObsCadOrcamento.setRows(5);
        jScrollPane1.setViewportView(txtAreaObsCadOrcamento);

        jbSalvarOrcamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbSalvarOrcamento.setText("Salvar");
        jbSalvarOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarOrcamentoActionPerformed(evt);
            }
        });

        jblimparOrcamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jblimparOrcamento.setText("Limpar");
        jblimparOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblimparOrcamentoActionPerformed(evt);
            }
        });

        jbCancOrcamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbCancOrcamento.setText("Cancelar");
        jbCancOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancOrcamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_text_areaLayout = new javax.swing.GroupLayout(jP_text_area);
        jP_text_area.setLayout(jP_text_areaLayout);
        jP_text_areaLayout.setHorizontalGroup(
            jP_text_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_text_areaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jP_text_areaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbSalvarOrcamento)
                .addGap(37, 37, 37)
                .addComponent(jblimparOrcamento)
                .addGap(37, 37, 37)
                .addComponent(jbCancOrcamento)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jP_text_areaLayout.setVerticalGroup(
            jP_text_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_text_areaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jP_text_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSalvarOrcamento)
                    .addComponent(jblimparOrcamento)
                    .addComponent(jbCancOrcamento))
                .addGap(0, 33, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 2, 2);
        jPCentro.add(jP_text_area, gridBagConstraints);

        txtDiscriOrcamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDiscriOrcamento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 273;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(54, 10, 0, 0);
        jPCentro.add(txtDiscriOrcamento, gridBagConstraints);

        txtTelCadOrcamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtTelCadOrcamento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 273;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 0, 0);
        jPCentro.add(txtTelCadOrcamento, gridBagConstraints);

        txtEmpOrcamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtEmpOrcamento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 273;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 10, 0, 0);
        jPCentro.add(txtEmpOrcamento, gridBagConstraints);

        jDChooser.setDateFormatString("dd/MM/yyyy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 185;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 0, 0);
        jPCentro.add(jDChooser, gridBagConstraints);

        getContentPane().add(jPCentro, java.awt.BorderLayout.LINE_END);

        jTitulo.setBackground(new java.awt.Color(102, 102, 102));
        jTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_img_titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/budget32.png"))); // NOI18N
        jTitulo.add(jLabel_img_titulo);

        jLabel_titulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_titulo.setText("ORÇAMENTO");
        jTitulo.add(jLabel_titulo);

        getContentPane().add(jTitulo, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarOrcamentoActionPerformed

        if (jbSalvarOrcamento.getText().equals("Salvar")) {
            Salvar();
            this.dispose();
        } else {
            Editar();
            this.dispose();
        }
    }//GEN-LAST:event_jbSalvarOrcamentoActionPerformed

    private void jbCancOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancOrcamentoActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancOrcamentoActionPerformed

    private void jblimparOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblimparOrcamentoActionPerformed
        clean();
    }//GEN-LAST:event_jblimparOrcamentoActionPerformed
    public void clean() {
        txtDiscriOrcamento.setText(" ");
        jDChooser.setDate(null);
        txtTelCadOrcamento.setText(" ");
        txtAreaObsCadOrcamento.setText(" ");
        txtEmpOrcamento.setText(" ");
    }

    public void verificar() {
        if (txtDiscriOrcamento.getText().trim().isEmpty() || txtTelCadOrcamento.getText().trim().isEmpty() || txtAreaObsCadOrcamento.getText().trim().isEmpty() || txtEmpOrcamento.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Atencao campos vazio ......");
        }
    }

    public void Salvar() {
        OrcamentoDao odao = new OrcamentoDao();
        Orcamento o = new Orcamento();
        if (txtDiscriOrcamento.getText().trim().isEmpty() || txtTelCadOrcamento.getText().trim().isEmpty() || txtAreaObsCadOrcamento.getText().trim().isEmpty() || txtEmpOrcamento.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Atencao campos vazio......");

        } else {
            o.setDiscricao(txtDiscriOrcamento.getText());
            o.setEmpresa(txtEmpOrcamento.getText());
            o.setTelefone(txtTelCadOrcamento.getText());
            Date date = new Date(jDChooser.getDate().getTime());
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            o.setDate(date);
            o.setObs(txtAreaObsCadOrcamento.getText());
            odao.inserir(o);
            frm.panelConsultaAberto();
        }

    }

    public void Editar() {
        OrcamentoDao odao = new OrcamentoDao();
        Orcamento o = new Orcamento();
        o.setCod(codigoAtualizacao);
        o.setDiscricao(txtDiscriOrcamento.getText());
        o.setEmpresa(txtEmpOrcamento.getText());
        o.setTelefone(txtTelCadOrcamento.getText());
        o.setDate(jDChooser.getDate());
        o.setObs(txtAreaObsCadOrcamento.getText());
        odao.atualiza(o);
        frm.panelConsultaAberto();

    }

    public void teste() {
        JOptionPane.showMessageDialog(null, "nao implementado \n Aguarde....");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaOrcamento dialog = new TelaOrcamento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_img_titulo;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JPanel jPCentro;
    private javax.swing.JPanel jP_text_area;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jTitulo;
    private javax.swing.JButton jbCancOrcamento;
    private javax.swing.JButton jbSalvarOrcamento;
    private javax.swing.JButton jblimparOrcamento;
    private javax.swing.JTextArea txtAreaObsCadOrcamento;
    private javax.swing.JTextField txtDiscriOrcamento;
    private javax.swing.JTextField txtEmpOrcamento;
    private javax.swing.JTextField txtTelCadOrcamento;
    // End of variables declaration//GEN-END:variables
}
