/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author Automacao
 */
public class TelaAbout extends javax.swing.JDialog {

    /**
     * Creates new form TelaAbout
     */
    public TelaAbout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTitulo = new javax.swing.JPanel();
        jL_img_logo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_dados_software = new javax.swing.JTextArea();
        jB_fechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jL_img_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logotipo_base.JPG"))); // NOI18N
        jL_img_logo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTitulo.add(jL_img_logo);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("<html>\n<p>&nbsp;</p>\n\n<p><span style=\"font-size:12px\"><span style=\"font-family:arial,helvetica,sans-serif\">Software <strong>Easy Mait</strong>&nbsp;desenvolvido para o componente curricular PROJETO INTEGRADOR VI&nbsp; EAD</span></span></p>\n\n<p><span style=\"font-size:12px\">da Universidade do Vale do Taquari - UNIVATES.</span></p>\n\n<p>&nbsp;</p>\n\n<p>Professor: <strong>FABR&Iacute;CIO PRETTO</strong></p>\n\n<p>Tutor: <strong>ADRIEL SECCO</strong></p>\n\n<p>&nbsp;</p>\n\n<p><span style=\"font-size:12px\">Nome do Grupo: <strong>Data Mining</strong></span></p>\n\n<p><span style=\"font-size:12px\">Integrantes :</span></p>\n\n<ul>\n\t<li><span style=\"font-size:12px\">Paulo Roberto de Oliveira</span></li>\n\t<li><span style=\"font-size:12px\">David Porn</span></li>\n\t<li><span style=\"font-size:12px\">Gabriel Trautmann Moraes</span></li>\n</ul>\n\n<p>&nbsp;</p>\n</html>");
        jTitulo.add(jLabel3);

        getContentPane().add(jTitulo, java.awt.BorderLayout.PAGE_START);

        jPCentro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jT_dados_software.setColumns(20);
        jT_dados_software.setRows(5);
        jT_dados_software.setText("Software: Easy Mait (Manutenção Fácil) - Organização e Economia\nVersão da Aplicação: 1.3\nIDE: Apache NetBeans IDE 10.0 (Build incubator-netbeans-release-380-on-20181217)\nJava: 11.0.3; Java HotSpot(TM) 64-Bit Server VM 11.0.3+12-LTS\nRuntime: Java(TM) SE Runtime Environment 11.0.3+12-LTS\nSystem: Windows 7 version 6.1 running on amd64; Cp1252; pt_BR (nb)\nTipo de Licença: FREE\n");
        jT_dados_software.setFocusable(false);
        jScrollPane1.setViewportView(jT_dados_software);

        jB_fechar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jB_fechar.setText("Fechar");
        jB_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_fecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCentroLayout = new javax.swing.GroupLayout(jPCentro);
        jPCentro.setLayout(jPCentroLayout);
        jPCentroLayout.setHorizontalGroup(
            jPCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCentroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jB_fechar)
                .addGap(401, 401, 401))
        );
        jPCentroLayout.setVerticalGroup(
            jPCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jB_fechar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPCentro, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_fecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_jB_fecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaAbout dialog = new TelaAbout(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_fechar;
    private javax.swing.JLabel jL_img_logo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPCentro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jT_dados_software;
    private javax.swing.JPanel jTitulo;
    // End of variables declaration//GEN-END:variables
}
