/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controle.Fornecedor;
import javax.swing.JOptionPane;
import modelo.FornecedorDao;

/**
 *
 * @author Olivercom
 */
public class TelaFornecedor extends javax.swing.JDialog {
FrmPrincipal f = new FrmPrincipal();
 int codigoAtualizacao;
    /**
     * Creates new form TelaFornecedor
     */
    public TelaFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public TelaFornecedor(Fornecedor c){
        initComponents();
     codigoAtualizacao = c.getCod();
      txtNomeCadFornecedor.setText(c.getEmpresa().toString());
      txtDocCadFornecedor.setText(c.getDocumento().toString());
       txtRespCadFornecedor.setText(c.getResponsavel().toString());
       txtEndCadFornecedor.setText(c.getEndereco().toString());
      txtTelCadFornecedor.setText(c.getTelefone().toString());
       txtCidCadFornecedor.setText(c.getCidade().toString());
       jbSalvarCadFornecedor.setText("ATUALIZAR");
        
        
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPCentro = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTelCadFornecedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNomeCadFornecedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDocCadFornecedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRespCadFornecedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEndCadFornecedor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCidCadFornecedor = new javax.swing.JTextField();
        jbSalvarCadFornecedor = new javax.swing.JButton();
        jbLimparCadFornecedor = new javax.swing.JButton();
        jbCanCadFornecedor = new javax.swing.JButton();
        jPTitulo = new javax.swing.JPanel();
        jL_img_titulo = new javax.swing.JLabel();
        jLabel_titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPCentro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPCentro.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Responsável :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 31, 0, 0);
        jPCentro.add(jLabel4, gridBagConstraints);

        txtTelCadFornecedor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtTelCadFornecedor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 228;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPCentro.add(txtTelCadFornecedor, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Razao Social :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 31, 0, 0);
        jPCentro.add(jLabel1, gridBagConstraints);

        txtNomeCadFornecedor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNomeCadFornecedor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 228;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 10, 0, 0);
        jPCentro.add(txtNomeCadFornecedor, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("RG/Cpf/Cnpj :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 31, 0, 0);
        jPCentro.add(jLabel2, gridBagConstraints);

        txtDocCadFornecedor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDocCadFornecedor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 228;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPCentro.add(txtDocCadFornecedor, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Endereço :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 31, 0, 0);
        jPCentro.add(jLabel3, gridBagConstraints);

        txtRespCadFornecedor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtRespCadFornecedor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 228;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPCentro.add(txtRespCadFornecedor, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Telefone :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 31, 0, 0);
        jPCentro.add(jLabel6, gridBagConstraints);

        txtEndCadFornecedor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtEndCadFornecedor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 228;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPCentro.add(txtEndCadFornecedor, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Cidade :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 31, 0, 0);
        jPCentro.add(jLabel7, gridBagConstraints);

        txtCidCadFornecedor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCidCadFornecedor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 228;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPCentro.add(txtCidCadFornecedor, gridBagConstraints);

        jbSalvarCadFornecedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbSalvarCadFornecedor.setText("salvar");
        jbSalvarCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarCadFornecedorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 77, 27, 0);
        jPCentro.add(jbSalvarCadFornecedor, gridBagConstraints);

        jbLimparCadFornecedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbLimparCadFornecedor.setText("limpar");
        jbLimparCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparCadFornecedorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 32, 27, 0);
        jPCentro.add(jbLimparCadFornecedor, gridBagConstraints);

        jbCanCadFornecedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbCanCadFornecedor.setText("Cancelar");
        jbCanCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCanCadFornecedorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 34, 27, 53);
        jPCentro.add(jbCanCadFornecedor, gridBagConstraints);

        getContentPane().add(jPCentro, java.awt.BorderLayout.CENTER);

        jPTitulo.setBackground(new java.awt.Color(102, 102, 102));

        jL_img_titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/trucking32.png"))); // NOI18N
        jPTitulo.add(jL_img_titulo);

        jLabel_titulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_titulo.setText("CADASTRO DE FORNECEDOR");
        jPTitulo.add(jLabel_titulo);

        getContentPane().add(jPTitulo, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarCadFornecedorActionPerformed
        if(jbSalvarCadFornecedor.getText().equalsIgnoreCase("salvar")){
            Salvar();
        }else
        {
            editar();
        }
        this.dispose();
    }//GEN-LAST:event_jbSalvarCadFornecedorActionPerformed

    private void jbCanCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCanCadFornecedorActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCanCadFornecedorActionPerformed

    private void jbLimparCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparCadFornecedorActionPerformed
       clean();
    }//GEN-LAST:event_jbLimparCadFornecedorActionPerformed
    public void clean(){
     txtNomeCadFornecedor.setText("");
     txtDocCadFornecedor.setText("");
     txtRespCadFornecedor.setText("");
     txtTelCadFornecedor.setText("");
     txtEndCadFornecedor.setText("");
     txtCidCadFornecedor.setText("");
    }
    public void teste(){
        JOptionPane.showMessageDialog(null, "nao implementado \n Aguarde....");
    }
    public void Salvar(){
        Fornecedor c = new Fornecedor();
        FornecedorDao cd= new FornecedorDao();
       
        c.setEmpresa(txtNomeCadFornecedor.getText());
        c.setDocumento(txtDocCadFornecedor.getText());
        c.setResponsavel(txtRespCadFornecedor.getText());
        c.setTelefone(txtTelCadFornecedor.getText());
        c.setEndereco(txtEndCadFornecedor.getText());
        c.setCidade(txtCidCadFornecedor.getText());
        cd.inserir(c);
        f.preencherTableOrcamento();
        clean();
        this.dispose();
       
    }
    public void editar(){
        Fornecedor c = new Fornecedor();
        FornecedorDao cd= new FornecedorDao();
        c.setCod(codigoAtualizacao);
        c.setEmpresa(txtNomeCadFornecedor.getText());
        c.setDocumento(txtDocCadFornecedor.getText());
        c.setResponsavel(txtRespCadFornecedor.getText());
        c.setTelefone(txtTelCadFornecedor.getText());
        c.setEndereco(txtEndCadFornecedor.getText());
        c.setCidade(txtCidCadFornecedor.getText());
        cd.atualiza(c);
        f.preencherTableOrcamento();
        clean();
        this.dispose();
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaFornecedor dialog = new TelaFornecedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_img_titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JPanel jPCentro;
    private javax.swing.JPanel jPTitulo;
    private javax.swing.JButton jbCanCadFornecedor;
    private javax.swing.JButton jbLimparCadFornecedor;
    private javax.swing.JButton jbSalvarCadFornecedor;
    private javax.swing.JTextField txtCidCadFornecedor;
    private javax.swing.JTextField txtDocCadFornecedor;
    private javax.swing.JTextField txtEndCadFornecedor;
    private javax.swing.JTextField txtNomeCadFornecedor;
    private javax.swing.JTextField txtRespCadFornecedor;
    private javax.swing.JTextField txtTelCadFornecedor;
    // End of variables declaration//GEN-END:variables
}
