/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Olivercom
 */
public class TelaOrcamento extends javax.swing.JDialog {

    /**
     * Creates new form TelaOrcamento
     */
    public TelaOrcamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPCentro = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtDataCadOrcamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDiscriOrcamento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTelCadOrcamento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComEmpCadOrcamento = new javax.swing.JComboBox<>();
        jbSalvarOrcamento = new javax.swing.JButton();
        jblimparOrcamento = new javax.swing.JButton();
        jbCancOrcamento = new javax.swing.JButton();
        jP_text_area = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaObsCadOrcamento = new javax.swing.JTextArea();
        jTitulo = new javax.swing.JPanel();
        jLabel_img_titulo = new javax.swing.JLabel();
        jLabel_titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPCentro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPCentro.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Data :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 45, 0, 0);
        jPCentro.add(jLabel4, gridBagConstraints);

        txtDataCadOrcamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDataCadOrcamento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 273;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPCentro.add(txtDataCadOrcamento, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Discrição :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 45, 0, 0);
        jPCentro.add(jLabel1, gridBagConstraints);

        txtDiscriOrcamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDiscriOrcamento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 273;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 10, 0, 0);
        jPCentro.add(txtDiscriOrcamento, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Empresa :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 45, 0, 0);
        jPCentro.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Telefone :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 45, 0, 0);
        jPCentro.add(jLabel3, gridBagConstraints);

        txtTelCadOrcamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtTelCadOrcamento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 273;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPCentro.add(txtTelCadOrcamento, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Observações :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 45, 0, 0);
        jPCentro.add(jLabel6, gridBagConstraints);

        jComEmpCadOrcamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 222;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPCentro.add(jComEmpCadOrcamento, gridBagConstraints);

        jbSalvarOrcamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbSalvarOrcamento.setText("Salvar");
        jbSalvarOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarOrcamentoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 117, 33, 0);
        jPCentro.add(jbSalvarOrcamento, gridBagConstraints);

        jblimparOrcamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jblimparOrcamento.setText("Limpar");
        jblimparOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblimparOrcamentoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 37, 33, 0);
        jPCentro.add(jblimparOrcamento, gridBagConstraints);

        jbCancOrcamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbCancOrcamento.setText("Cancelar");
        jbCancOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancOrcamentoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 37, 33, 0);
        jPCentro.add(jbCancOrcamento, gridBagConstraints);

        txtAreaObsCadOrcamento.setColumns(20);
        txtAreaObsCadOrcamento.setRows(5);
        jScrollPane1.setViewportView(txtAreaObsCadOrcamento);

        javax.swing.GroupLayout jP_text_areaLayout = new javax.swing.GroupLayout(jP_text_area);
        jP_text_area.setLayout(jP_text_areaLayout);
        jP_text_areaLayout.setHorizontalGroup(
            jP_text_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_text_areaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jP_text_areaLayout.setVerticalGroup(
            jP_text_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_text_areaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 49);
        jPCentro.add(jP_text_area, gridBagConstraints);

        getContentPane().add(jPCentro, java.awt.BorderLayout.CENTER);

        jTitulo.setBackground(new java.awt.Color(102, 102, 102));
        jTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_img_titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/budget32.png"))); // NOI18N
        jTitulo.add(jLabel_img_titulo);

        jLabel_titulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_titulo.setText("ORÇAMENTO");
        jTitulo.add(jLabel_titulo);

        getContentPane().add(jTitulo, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarOrcamentoActionPerformed
    teste();
       
    }//GEN-LAST:event_jbSalvarOrcamentoActionPerformed

    private void jbCancOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancOrcamentoActionPerformed
       this.dispose();
    }//GEN-LAST:event_jbCancOrcamentoActionPerformed

    private void jblimparOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblimparOrcamentoActionPerformed
        clean();
    }//GEN-LAST:event_jblimparOrcamentoActionPerformed
    public void clean(){
     txtDiscriOrcamento.setText("");
     txtDataCadOrcamento.setText("");
     txtTelCadOrcamento.setText("");
     txtAreaObsCadOrcamento.setText("");
     jComEmpCadOrcamento.getModel().setSelectedItem("");
    }
    public void teste(){
        JOptionPane.showMessageDialog(null, "nao implementado \n Aguarde....");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaOrcamento dialog = new TelaOrcamento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComEmpCadOrcamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_img_titulo;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JPanel jPCentro;
    private javax.swing.JPanel jP_text_area;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jTitulo;
    private javax.swing.JButton jbCancOrcamento;
    private javax.swing.JButton jbSalvarOrcamento;
    private javax.swing.JButton jblimparOrcamento;
    private javax.swing.JTextArea txtAreaObsCadOrcamento;
    private javax.swing.JTextField txtDataCadOrcamento;
    private javax.swing.JTextField txtDiscriOrcamento;
    private javax.swing.JTextField txtTelCadOrcamento;
    // End of variables declaration//GEN-END:variables
}
